### ISSUE TITLE
stuck at "downloading data"

### ISSUE THREAD

**Issue by tenzap** [Zaczero/osm-relatify#22]
For some reason, sometimes I'm stuck at "downloading data" especially when the way that is added is long. Once in that state, nothing happens anymore.

Browser: Firefox 102.13.0esr

**Comment by Zaczero** [comment]
Hello!
Please provide me with the relation ID and indicate where the issue occurs, preferrably using an OpenStreetMap URL.

**Comment by Zaczero** [comment]
> Seems browser related, because I switched to opera (chrome engine) and there it worked. I finished my work with JOSM but I'm pretty sure you can reproduce this with any relation as long as you do it on firefox.

I did try it with normal Firefox and worked just fine. Maybe it's something with an ESR edition. I'll check it on the next occasion.

**Comment by Zaczero** [comment]
This is Firefox ESR specific issue.

The error says: `ReferenceError: CompressionStream is not defined`.
Which is supported in Firefox [since version 113](https://developer.mozilla.org/en-US/docs/Web/API/CompressionStream#browser_compatibility), ESR is at version 102.

I use this feature to compress the data as it being transmitted in a websocket and I will most likely not fix it unless more people report the same issue. This would require changing the behavior on both frontend and backend endpoints. Sorry!
