### ISSUE TITLE
Duplicated roundabout

### ISSUE THREAD

**Issue by Dimitar5555** [Zaczero/osm-relatify#32]
I'm not sure how or why it might've happened, but the roundabout is somehow duplicated. On the west side it is quite segmented.

![image](https://github.com/Zaczero/osm-relatify/assets/19364673/1aac3c7e-f081-4efb-8ea1-98f551b61a7f)

All other segments are duplicated normally (from one exit/entrance to the next).

![image](https://github.com/Zaczero/osm-relatify/assets/19364673/9c724dd3-d025-4b46-a1b3-eb8041a10849)

The duplicate was introduced in https://www.osm.org/changeset/139108622 and I've removed it manually in https://www.osm.org/changeset/139125857.

**Comment by Zaczero** [comment]
This occurred because two edits were performed in very quick succession, which didn't allow Overpass a chance to synchronize. I believe this issue could be resolved by temporarily storing recent splits in memory and preventing the user from loading a new relation when the database hasn't been fully synchronized. Alternatively, an even more advanced merge logic could be implemented to detect and resolve situations like this.

https://www.openstreetmap.org/changeset/139108512
https://www.openstreetmap.org/changeset/139108622

Thank you for reporting the bug!

**Comment by zorun** [comment]
I have seen several instances of this bug in my neighbourhood recently, introduced by another contributor using osm-relatify.

The problem can be described like this:

- the roundabout is split into very small ways, sometimes 2-nodes ways even when there is no intersecting road. This is weird and annoying for other contributors, but not really harmful
- the ways of the roundabout are duplicated, with ways sitting on top of each other. Super confusing.
- the public transport relations are messed up, because they take the roundabout twice!

This is creating a mess in OSM and requires time to clean up, can you at least workaround the problem so that people don't trigger this bug? Like forcing a delay between edits?

Here is an example of duplicated ways exhibiting the issues that I haven't yet fixed:

- https://www.openstreetmap.org/way/1184234820
- https://www.openstreetmap.org/way/1184234236

**Comment by infeeeee** [comment]
This still happens on a lot of places. Is there any workaround to stop this happening? Hard reload the browser? How much time should I wait between edits?

**Comment by Zaczero** [comment]
> How much time should I wait between edits?

upload -> 3 minutes -> load

**Comment by Zaczero** [comment]
This issue will be resolved with [OpenStreetMap-NG](https://github.com/Zaczero/openstreetmap-ng) project.

**Comment by mutipg** [comment]
Maybe it would be possible to turn on a timer (e.g. in the form of a stopwatch) between edits in realtify and block the download of the relation for a user who has just sent one edit?

Sometimes I forget about the 3-minute rule and this creates unwanted duplicates.

**Comment by Zaczero** [comment]
I have added a conflict detection mechanism.

The issue should be now resolved :+1:. Sorry for keeping you waiting.

The message will look like:
Conflict: Way XXXXX was modified. Go back and click the relation reload button.

**Comment by mutipg** [comment]
The problem still persists. Yesterday, two editions of a similar bus route with an interval of 3 minutes generated duplicate sections of the route.

* 1st way created at 2024-10-03 21:36
https://pewu.github.io/osm-history/#/way/1320456812
* 2nd way created at 2024-10-03 21:39
https://pewu.github.io/osm-history/#/way/1320457384 (I deleted this one as duplicate already)

**Comment by Zaczero** [comment]
I will take a closer look at it, thanks for letting me know and sorry for the issue!

Additional info:

- This is the main way: https://www.openstreetmap.org/way/202789937/history v14, v15

**Comment by mutipg** [comment]
Maybe it would be worth starting some kind of timer before the next edition in Relatify. Many people probably already use this application and do not wait for the data to be updated on the Overpass server, creating duplicate lines.

Here is another such situation.
https://www.openstreetmap.org/changeset/157830755

**Comment by Zaczero** [comment]
Should be fixed now. After further investigation there was a type mismatch which caused the conflict check never to run. XML returns everything as text and Relatify was missing a cast to int before performing the comparison of new data.
